apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""] # inicate the core api group 
    resourses: ["pods"]
    verbs: ["get", "watch"]
