apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pod
  namespace: default
subjects:
  - kind: ServiceAccount
    name: demo-sa
    namespace: default
    apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
