apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secondapp
  template:
    metadata:
      labels:
        app: secondapp
    spec:
      containers:
      - name: testapp
        image: katacoda/docker-http-server
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: secondapp-svc
spec:
  selector:
    app: secondapp
  ports:
  - protocol: TCP
    port: 30022
    targetPort: 80

