apiVersion: apps/v1
kind: Deployment
metadata:
  name: thirdapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thirdapp
  template:
    metadata:
      labels:
        app: thirdapp
    spec:
      containers:
      - name: testapp
        image: katacoda/docker-http-server
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: thirdapp-svc
spec:
  selector:
    app: thirdapp
  ports:
  - protocol: TCP
    port: 30023
    targetPort: 80

