apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: second-app-ingress
  annotations:
spec:
  ingressClassName: public 
  rules:
   - http:      
      paths:
      - pathType: Prefix
        path: "/v2"
        backend:
          service:
            name: secondapp-svc
            port: 
              number: 30022
