apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: third-app-ingress
  annotations:
spec:
  ingressClassName: pub 
  rules:
   - http:      
      paths:
      - pathType: Prefix
        path: "/v3"
        backend:
          service:
            name: thirdapp-svc
            port: 
              number: 30023
